In [ ]:
print('Hello')

Hello


In [ ]:
#my second line

In [ ]:
s='Hello Swarnali'
print(s)
type (s) #type of character
print(type(s)) #wipes off the previous type output

Hello Swarnali
<class 'str'>


In [ ]:
s=1.0
type (s)
#print(type(s))

float

In [ ]:
#2. string manipulation
s="hello"
print (s)
print (s[0], s[1], s[2], s[-2], s[-1], len(s))
print (s+" world"+" I am Swarnali")

hello
h e l l o 5
hello world I am Swarnali


In [ ]:
# String is immutable
s='Hello'
print(s)
type(s)
s[1]='b' #error Since s[1] is "e" so it cannot be b

Hello


TypeError: ignored

In [ ]:
# Strings and integer

s="hello"
num=10
print(num)
#print (s+num) # error string cant be added to integer

print (s + str ( num))

10
hello10


In [ ]:
s="hello"
num=10
print(num)
t=str ( num)
print(s+t)

10
hello10


In [ ]:
#5. String methods

s ="Hello"
print (str.lower(s))
print (s.upper())
print (str.strip(s))
print (str.isalpha(s))
print (str.isdigit(s))
print (str.isspace(s))
print(s.replace(s, 'old'))
'a,b,c'.split(',')
':'.join(['a','b','c'])

hello
HELLO
Hello
True
False
False
old


'a:b:c'

In [ ]:
s ="Hello"
print(s[1:3])
print('\n')

print(s[1:])
print('\n')
print(s[-4:3])
print('\n')

el


ello


el




In [ ]:
#
str1='hello %s, %d' % ('world', 10) #s for string d for integer
print(str1)

hello world, 10


In [ ]:
str2 = 'Hello {}, {}'. format('world',10)
print(str2)
str3 = 'Hello {wd}, {num}'. format(num=10,wd='hjj')
print(str3)
str4='Hello {wd:10}, {num:.3f}'.format(num=10.0, wd='World') # .3f float 3 decimals #wd:10 means 10 spaces
print(str4)

Hello world, 10
Hello hjj, 10
Hello World     , 10.000


In [ ]:
#If
num = 4
if num < 5:
  print('num is smaller than 5')
if num > 5:
  print('num is greater than 5')
elif num == 5:
  print('num is 5')
else:
  print('num is smaller than 5')

num is smaller than 5
num is smaller than 5


In [ ]:
num = 5
if num < 5:
  print('num is smaller than 5')
if num > 5:
  print('num is greater than 5')
elif num == 5:
  print('num is 5')
else:
  print('num is smaller than 5')

num is 5


In [ ]:
#Function Calls

print(type(32))
type(32)
print(int(32))
#int ('Hello')
print(int(-2.8))
import math
print(math.sin(3.1416))
print(math.cos(3.1416))
print(math.asin(0.5))  #sin inverse
print(math.sqrt(2))
#help('math')

<class 'int'>
32
-2
-7.346410206643587e-06
-0.9999999999730151
0.5235987755982989
1.4142135623730951


In [ ]:
import numpy as np
print(np.pi)

3.141592653589793


In [ ]:
help('math')

Help on built-in module math:

NAME
    math

DESCRIPTION
    This module provides access to the mathematical functions
    defined by the C standard.

FUNCTIONS
    acos(x, /)
        Return the arc cosine (measured in radians) of x.
        
        The result is between 0 and pi.
    
    acosh(x, /)
        Return the inverse hyperbolic cosine of x.
    
    asin(x, /)
        Return the arc sine (measured in radians) of x.
        
        The result is between -pi/2 and pi/2.
    
    asinh(x, /)
        Return the inverse hyperbolic sine of x.
    
    atan(x, /)
        Return the arc tangent (measured in radians) of x.
        
        The result is between -pi/2 and pi/2.
    
    atan2(y, x, /)
        Return the arc tangent (measured in radians) of y/x.
        
        Unlike atan(y/x), the signs of both x and y are considered.
    
    atanh(x, /)
        Return the inverse hyperbolic tangent of x.
    
    ceil(x, /)
        Return the ceiling of x as an Integral.
      

In [ ]:
print (math.ceil(3.2))
print (math.comb(6, 5))
print (math.floor(3.2))

4
6
3


In [ ]:
# def function
def name():
  print("I am Swarnali")
  print("yay")
name()

I am Swarnali
yay


In [ ]:
# Function parameters and arguments

def print_twice(arg1):
  print(arg1)
  print(arg1)

print_twice(math.pi)
print_twice('Spam' *4)

3.141592653589793
3.141592653589793
SpamSpamSpamSpam
SpamSpamSpamSpam


In [ ]:
#Function returns
def print_twice(arg1):
  print(arg1)
  print(arg1)

result = print_twice('Bing')
print(result) #Gives none since we do not return anything in the function

Bing
Bing
None


In [ ]:
def print_twice(arg1,arg2):
  print(arg1)
  print(arg2)
  return arg1,arg2
res1, res2 = print_twice('Bing',' S')
print(res1)
print(res2)

Bing
 S
Bing
 S


In [ ]:
# Importing with 'from' function

import math
print (math)
print (math.pi)
#print(pi)

<module 'math' (built-in)>
3.141592653589793


In [ ]:
def factorial (n):
  if not isinstance(n, int):
    print('Factorial is only defined for integers.')
    return None
  elif n < 0:
    print('negative')
    return None

  elif n==0:
    return 1

  else:
    return n*factorial(n-1) # Recursively

factorial(5)

120

In [ ]:
#Default arguments

def func1(arg1,arg2=None):
  if arg2 is None:
    print(arg1)
  else:
    print(arg1,arg2)
func1('hello')

func1('hello', 'world')

hello
hello world


In [ ]:
# Global loacl variables

global_var = 10

def func1():
    global_var = 100
func1()


global_var

10

In [ ]:
global_var = 1
def func2():
  global global_var
  global_var = 3

func2()
global_var

3

In [ ]:
a=2;
b=5;
c=(a**2+b**2)**(0.5);
d=math.sqrt(c)
print('Hypo c=' , c)
print ('square root d =' , d)
e = math.log(d)
print(e)
f=c*d
g=c/d
print(f)
print(g)
h=a*math.sin(b)
print(h)
u=int(d)
factorial(u)

Hypo c= 5.385164807134504
square root d = 2.320595787106084
0.8418239574966185
12.496790764308276
2.3205957871060834
-1.917848549326277


2

In [ ]:
# Matrices

from scipy import *
from numpy import *

M1=array([[1,2,3],[3,4,5],[1,2,1]])
#M2=array([[0,1,2],[3,4,5],[7,8,9]])

#M3=M1*M2 # element wise multiplication
#M4=array([[1],[2],[3]])
#M5=M1*M4
print(np.linalg.inv(M1))
print('\n M1=', M1)
#print('\n M4=', M4)
#print('\n M5=', M5)

[[-1.5  1.  -0.5]
 [ 0.5 -0.5  1. ]
 [ 0.5 -0.  -0.5]]

 M1= [[1 2 3]
 [3 4 5]
 [1 2 1]]
